/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mfh684
 */
import java.io.Serializable;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import lombok.Getter;
import lombok.Setter;
import org.dutyroster.hibernate.database.Center;
import org.dutyroster.web.services.PreOrientationService;
 
@ManagedBean(name="userBean")
@SessionScoped
public class UserBean implements Serializable{
 
	public String favCoffee1;
	public String favCoffee2;
	public String favCoffee3;
 
	public String getFavCoffee1() {
		return favCoffee1;
	}
 
	public void setFavCoffee1(String favCoffee1) {
		this.favCoffee1 = favCoffee1;
	}
 
	public String getFavCoffee2() {
		return favCoffee2;
	}
 
	public void setFavCoffee2(String favCoffee2) {
		this.favCoffee2 = favCoffee2;
	}
 
	public String getFavCoffee3() {
		return favCoffee3;
	}
 
	public void setFavCoffee3(String favCoffee3) {
		this.favCoffee3 = favCoffee3;
	}
 
	//Generated by Map
	private static Map<String,Object> coffee2Value;
	static{
		coffee2Value = new LinkedHashMap<String,Object>();
		coffee2Value.put("Coffee2 - Cream Latte", "Cream Latte"); //label, value
		coffee2Value.put("Coffee2 - Extreme Mocha", "Extreme Mocha");
		coffee2Value.put("Coffee2 - Buena Vista", "Buena Vista");
	}
 
	public Map<String,Object> getFavCoffee2Value() {
		return coffee2Value;
	}
 
	//Generated by Object array
	public static class Coffee{
                @Getter@Setter
                public Short id;
		public String coffeeLabel;
		public String coffeeValue;
 
		public Coffee(Short id,String coffeeLabel, String coffeeValue){
                    this.id=id;
			this.coffeeLabel = coffeeLabel;
			this.coffeeValue = coffeeValue;
		}
 
		public String getCoffeeLabel(){
			return coffeeLabel;
		}
 
		public String getCoffeeValue(){
			return coffeeValue;
		}
 
	}
 
	public List<Center> coffee3List;
 
	public List<Center> getFavCoffee3Value() {
 
//		coffee3List = new Coffee[3];
//		coffee3List[0] = new Coffee(Short.valueOf("1"),"Coffee3 - Cream Latte", "Cream Latte");
//		coffee3List[1] = new Coffee(Short.valueOf("2"),"Coffee3 - Extreme Mocha", "Extreme Mocha");
//		coffee3List[2] = new Coffee(Short.valueOf("3"),"Coffee3 - Buena Vista", "Buena Vista");
           // coffee3List = new PreOrientationService().getCenters();
 
		return coffee3List;
 
	}
        public Object save(){
            System.out.println("Selected Center is : "+favCoffee3);
            return null;
        }
 
}
