package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * DayType generated by hbm2java
 */
public class DayType  implements java.io.Serializable {


     private Short dayTypeId;
     private String dayTypeName;

    public DayType() {
    }

    public DayType(String dayTypeName) {
       this.dayTypeName = dayTypeName;
    }
   
    public Short getDayTypeId() {
        return this.dayTypeId;
    }
    
    public void setDayTypeId(Short dayTypeId) {
        this.dayTypeId = dayTypeId;
    }
    public String getDayTypeName() {
        return this.dayTypeName;
    }
    
    public void setDayTypeName(String dayTypeName) {
        this.dayTypeName = dayTypeName;
    }




}


