package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * DayTypeWeghtageId generated by hbm2java
 */
public class DayTypeWeghtageId  implements java.io.Serializable {


     private Center centreId;
     private Workstation workstationId;
     private DayType dayTypeId;

    public DayTypeWeghtageId() {
    }

    public DayTypeWeghtageId(Center centreId, Workstation workstationId, DayType dayTypeId) {
       this.centreId = centreId;
       this.workstationId = workstationId;
       this.dayTypeId = dayTypeId;
    }
   
    public Center getCentreId() {
        return this.centreId;
    }
    
    public void setCentreId(Center centreId) {
        this.centreId = centreId;
    }
    public Workstation getWorkstationId() {
        return this.workstationId;
    }
    
    public void setWorkstationId(Workstation workstationId) {
        this.workstationId = workstationId;
    }
    public DayType getDayTypeId() {
        return this.dayTypeId;
    }
    
    public void setDayTypeId(DayType dayTypeId) {
        this.dayTypeId = dayTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DayTypeWeghtageId) ) return false;
		 DayTypeWeghtageId castOther = ( DayTypeWeghtageId ) other; 
         
		 return (this.getCentreId()==castOther.getCentreId())
 && (this.getWorkstationId()==castOther.getWorkstationId())
 && (this.getDayTypeId()==castOther.getDayTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.centreId.getCenterId();
         result = 37 * result + this.workstationId.getWorkstationId();
         result = 37 * result + this.dayTypeId.getDayTypeId();
         return result;
   }   


}


