package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * DayTypeWeghtageId generated by hbm2java
 */
public class DayTypeWeghtageId  implements java.io.Serializable {


     private short centreId;
     private short workstationId;
     private short dayTypeId;

    public DayTypeWeghtageId() {
    }

    public DayTypeWeghtageId(short centreId, short workstationId, short dayTypeId) {
       this.centreId = centreId;
       this.workstationId = workstationId;
       this.dayTypeId = dayTypeId;
    }
   
    public short getCentreId() {
        return this.centreId;
    }
    
    public void setCentreId(short centreId) {
        this.centreId = centreId;
    }
    public short getWorkstationId() {
        return this.workstationId;
    }
    
    public void setWorkstationId(short workstationId) {
        this.workstationId = workstationId;
    }
    public short getDayTypeId() {
        return this.dayTypeId;
    }
    
    public void setDayTypeId(short dayTypeId) {
        this.dayTypeId = dayTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DayTypeWeghtageId) ) return false;
		 DayTypeWeghtageId castOther = ( DayTypeWeghtageId ) other; 
         
		 return (this.getCentreId()==castOther.getCentreId())
 && (this.getWorkstationId()==castOther.getWorkstationId())
 && (this.getDayTypeId()==castOther.getDayTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCentreId();
         result = 37 * result + this.getWorkstationId();
         result = 37 * result + this.getDayTypeId();
         return result;
   }   


}


