package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Short deptId;
     private String deptName;
     private String deptHead;
     private Set<PreOrientation> preOrientations = new HashSet<PreOrientation>(0);
     private Set<LearningToLearn> learningToLearns = new HashSet<LearningToLearn>(0);
     private Set<StaffMember> staffMembers = new HashSet<StaffMember>(0);
     private Set<Registration> registrations = new HashSet<Registration>(0);

    public Department() {
    }

	
    public Department(String deptName, String deptHead) {
        this.deptName = deptName;
        this.deptHead = deptHead;
    }
    public Department(String deptName, String deptHead, Set<PreOrientation> preOrientations, Set<LearningToLearn> learningToLearns, Set<StaffMember> staffMembers, Set<Registration> registrations) {
       this.deptName = deptName;
       this.deptHead = deptHead;
       this.preOrientations = preOrientations;
       this.learningToLearns = learningToLearns;
       this.staffMembers = staffMembers;
       this.registrations = registrations;
    }
   
    public Short getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(Short deptId) {
        this.deptId = deptId;
    }
    public String getDeptName() {
        return this.deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    public String getDeptHead() {
        return this.deptHead;
    }
    
    public void setDeptHead(String deptHead) {
        this.deptHead = deptHead;
    }
    public Set<PreOrientation> getPreOrientations() {
        return this.preOrientations;
    }
    
    public void setPreOrientations(Set<PreOrientation> preOrientations) {
        this.preOrientations = preOrientations;
    }
    public Set<LearningToLearn> getLearningToLearns() {
        return this.learningToLearns;
    }
    
    public void setLearningToLearns(Set<LearningToLearn> learningToLearns) {
        this.learningToLearns = learningToLearns;
    }
    public Set<StaffMember> getStaffMembers() {
        return this.staffMembers;
    }
    
    public void setStaffMembers(Set<StaffMember> staffMembers) {
        this.staffMembers = staffMembers;
    }
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }




}


