package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Holiday generated by hbm2java
 */
public class Holiday  implements java.io.Serializable {


     private Short holidayId;
     private Date holiday;
     private String holidayType;

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 83 * hash + (this.holidayId != null ? this.holidayId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Holiday other = (Holiday) obj;
        if (this.holidayId != other.holidayId && (this.holidayId == null || !this.holidayId.equals(other.holidayId))) {
            return false;
        }
        return true;
    }

    public Holiday() {
    }

	
    public Holiday(String holidayType) {
        this.holidayType = holidayType;
    }
    public Holiday(Date holiday, String holidayType) {
       this.holiday = holiday;
       this.holidayType = holidayType;
    }
   
    public Short getHolidayId() {
        return this.holidayId;
    }
    
    public void setHolidayId(Short holidayId) {
        this.holidayId = holidayId;
    }
    public Date getHoliday() {
        return this.holiday;
    }
    
    public void setHoliday(Date holiday) {
        this.holiday = holiday;
    }
    public String getHolidayType() {
        return this.holidayType;
    }
    
    public void setHolidayType(String holidayType) {
        this.holidayType = holidayType;
    }




}


