package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * LearningAlertHistoryId generated by hbm2java
 */
public class LearningAlertHistoryId  implements java.io.Serializable {


     private short staffId;
     private short lerId;
     private short alertId;

    public LearningAlertHistoryId() {
    }

    public LearningAlertHistoryId(short staffId, short lerId, short alertId) {
       this.staffId = staffId;
       this.lerId = lerId;
       this.alertId = alertId;
    }
   
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }
    public short getLerId() {
        return this.lerId;
    }
    
    public void setLerId(short lerId) {
        this.lerId = lerId;
    }
    public short getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(short alertId) {
        this.alertId = alertId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LearningAlertHistoryId) ) return false;
		 LearningAlertHistoryId castOther = ( LearningAlertHistoryId ) other; 
         
		 return (this.getStaffId()==castOther.getStaffId())
 && (this.getLerId()==castOther.getLerId())
 && (this.getAlertId()==castOther.getAlertId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStaffId();
         result = 37 * result + this.getLerId();
         result = 37 * result + this.getAlertId();
         return result;
   }   


}


