package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LearningToLearn generated by hbm2java
 */
public class LearningToLearn  implements java.io.Serializable {


     private Short lerId;
     private Department department;
     private Program program;
     private Session session;
     private Center center;
     private Date lerDate;
     private Date lerYear;

    public LearningToLearn() {
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.lerId != null ? this.lerId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LearningToLearn other = (LearningToLearn) obj;
        if (this.lerId != other.lerId && (this.lerId == null || !this.lerId.equals(other.lerId))) {
            return false;
        }
        return true;
    }

    public LearningToLearn(Department department, Program program, Session session, Center center, Date lerDate, Date lerYear) {
       this.department = department;
       this.program = program;
       this.session = session;
       this.center = center;
       this.lerDate = lerDate;
       this.lerYear = lerYear;
    }
   
    public Short getLerId() {
        return this.lerId;
    }
    
    public void setLerId(Short lerId) {
        this.lerId = lerId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }
    public Date getLerDate() {
        return this.lerDate;
    }
    
    public void setLerDate(Date lerDate) {
        this.lerDate = lerDate;
    }
    public Date getLerYear() {
        return this.lerYear;
    }
    
    public void setLerYear(Date lerYear) {
        this.lerYear = lerYear;
    }




}


