package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * LearningStaffId generated by hbm2java
 */
public class LearningStaffId  implements java.io.Serializable {


     private LearningToLearn lerId;
     private StaffMember staffId;

    public LearningStaffId() {
    }

    public LearningStaffId(LearningToLearn lerId, StaffMember staffId) {
       this.lerId = lerId;
       this.staffId = staffId;
    }
   
    public LearningToLearn getLerId() {
        return this.lerId;
    }
    
    public void setLerId(LearningToLearn lerId) {
        this.lerId = lerId;
    }
    public StaffMember getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(StaffMember staffId) {
        this.staffId = staffId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LearningStaffId) ) return false;
		 LearningStaffId castOther = ( LearningStaffId ) other; 
         
		 return (this.getLerId()==castOther.getLerId())
 && (this.getStaffId()==castOther.getStaffId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.lerId.getLerId();
         result = 37 * result + this.staffId.getStaffId();
         return result;
   }   


}


