package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * LearningStaffCat generated by hbm2java
 */
public class LearningStaffCat  implements java.io.Serializable {


     private LearningStaffCatId id;
     private int noOfMembers;
     private int vacantSlots;

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 13 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LearningStaffCat other = (LearningStaffCat) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    public LearningStaffCat() {
    }

    public LearningStaffCat(LearningStaffCatId id, int noOfMembers, int vacantSlots) {
       this.id = id;
       this.noOfMembers = noOfMembers;
       this.vacantSlots = vacantSlots;
    }
   
    public LearningStaffCatId getId() {
        return this.id;
    }
    
    public void setId(LearningStaffCatId id) {
        this.id = id;
    }
    public int getNoOfMembers() {
        return this.noOfMembers;
    }
    
    public void setNoOfMembers(int noOfMembers) {
        this.noOfMembers = noOfMembers;
    }
    public int getVacantSlots() {
        return this.vacantSlots;
    }
    
    public void setVacantSlots(int vacantSlots) {
        this.vacantSlots = vacantSlots;
    }




}


