package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * LearningAlertHistory generated by hbm2java
 */
public class LearningAlertHistory  implements java.io.Serializable {


     private LearningAlertHistoryId id;
     private Date date;
     private short sendingStatus;

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + (this.id != null ? this.id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LearningAlertHistory other = (LearningAlertHistory) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    public LearningAlertHistory() {
    }

    public LearningAlertHistory(LearningAlertHistoryId id, Date date, short sendingStatus) {
       this.id = id;
       this.date = date;
       this.sendingStatus = sendingStatus;
    }
   
    public LearningAlertHistoryId getId() {
        return this.id;
    }
    
    public void setId(LearningAlertHistoryId id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public short getSendingStatus() {
        return this.sendingStatus;
    }
    
    public void setSendingStatus(short sendingStatus) {
        this.sendingStatus = sendingStatus;
    }




}


