package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * LearningStaffCatId generated by hbm2java
 */
public class LearningStaffCatId  implements java.io.Serializable {


     private short lerId;
     private short staffCatId;

    public LearningStaffCatId() {
    }

    public LearningStaffCatId(short lerId, short staffCatId) {
       this.lerId = lerId;
       this.staffCatId = staffCatId;
    }
   
    public short getLerId() {
        return this.lerId;
    }
    
    public void setLerId(short lerId) {
        this.lerId = lerId;
    }
    public short getStaffCatId() {
        return this.staffCatId;
    }
    
    public void setStaffCatId(short staffCatId) {
        this.staffCatId = staffCatId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LearningStaffCatId) ) return false;
		 LearningStaffCatId castOther = ( LearningStaffCatId ) other; 
         
		 return (this.getLerId()==castOther.getLerId())
 && (this.getStaffCatId()==castOther.getStaffCatId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLerId();
         result = 37 * result + this.getStaffCatId();
         return result;
   }   


}


