package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * LearningStaffCat generated by hbm2java
 */
public class LearningStaffCat  implements java.io.Serializable {


     private LearningStaffCatId id;
     private int noOfMembers;
     private int vacantSlots;

    public LearningStaffCat() {
    }

    public LearningStaffCat(LearningStaffCatId id, int noOfMembers, int vacantSlots) {
       this.id = id;
       this.noOfMembers = noOfMembers;
       this.vacantSlots = vacantSlots;
    }
   
    public LearningStaffCatId getId() {
        return this.id;
    }
    
    public void setId(LearningStaffCatId id) {
        this.id = id;
    }
    public int getNoOfMembers() {
        return this.noOfMembers;
    }
    
    public void setNoOfMembers(int noOfMembers) {
        this.noOfMembers = noOfMembers;
    }
    public int getVacantSlots() {
        return this.vacantSlots;
    }
    
    public void setVacantSlots(int vacantSlots) {
        this.vacantSlots = vacantSlots;
    }




}


