package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * LearningStaffAvailability generated by hbm2java
 */
public class LearningStaffAvailability  implements java.io.Serializable {


     private LearningStaffAvailabilityId id;
     private short availability;

    public LearningStaffAvailability() {
    }

    public LearningStaffAvailability(LearningStaffAvailabilityId id, short availability) {
       this.id = id;
       this.availability = availability;
    }
   
    public LearningStaffAvailabilityId getId() {
        return this.id;
    }
    
    public void setId(LearningStaffAvailabilityId id) {
        this.id = id;
    }
    public short getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(short availability) {
        this.availability = availability;
    }




}


