package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * LearningStaffAvailabilityId generated by hbm2java
 */
public class LearningStaffAvailabilityId  implements java.io.Serializable {


     private short lerId;
     private short staffId;
     private short dayTypeId;

    public LearningStaffAvailabilityId() {
    }

    public LearningStaffAvailabilityId(short lerId, short staffId, short dayTypeId) {
       this.lerId = lerId;
       this.staffId = staffId;
       this.dayTypeId = dayTypeId;
    }
   
    public short getLerId() {
        return this.lerId;
    }
    
    public void setLerId(short lerId) {
        this.lerId = lerId;
    }
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }
    public short getDayTypeId() {
        return this.dayTypeId;
    }
    
    public void setDayTypeId(short dayTypeId) {
        this.dayTypeId = dayTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LearningStaffAvailabilityId) ) return false;
		 LearningStaffAvailabilityId castOther = ( LearningStaffAvailabilityId ) other; 
         
		 return (this.getLerId()==castOther.getLerId())
 && (this.getStaffId()==castOther.getStaffId())
 && (this.getDayTypeId()==castOther.getDayTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLerId();
         result = 37 * result + this.getStaffId();
         result = 37 * result + this.getDayTypeId();
         return result;
   }   


}


