package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * PreOrientationAlertHistoryId generated by hbm2java
 */
public class PreOrientationAlertHistoryId  implements java.io.Serializable {


     private short staffId;
     private short preId;
     private short alertId;

    public PreOrientationAlertHistoryId() {
    }

    public PreOrientationAlertHistoryId(short staffId, short preId, short alertId) {
       this.staffId = staffId;
       this.preId = preId;
       this.alertId = alertId;
    }
   
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }
    public short getPreId() {
        return this.preId;
    }
    
    public void setPreId(short preId) {
        this.preId = preId;
    }
    public short getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(short alertId) {
        this.alertId = alertId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PreOrientationAlertHistoryId) ) return false;
		 PreOrientationAlertHistoryId castOther = ( PreOrientationAlertHistoryId ) other; 
         
		 return (this.getStaffId()==castOther.getStaffId())
 && (this.getPreId()==castOther.getPreId())
 && (this.getAlertId()==castOther.getAlertId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStaffId();
         result = 37 * result + this.getPreId();
         result = 37 * result + this.getAlertId();
         return result;
   }   


}


