package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * PreOrientationStaffId generated by hbm2java
 */
public class PreOrientationStaffId  implements java.io.Serializable {


     private short preId;
     private short staffId;

    public PreOrientationStaffId() {
    }

    public PreOrientationStaffId(short preId, short staffId) {
       this.preId = preId;
       this.staffId = staffId;
    }
   
    public short getPreId() {
        return this.preId;
    }
    
    public void setPreId(short preId) {
        this.preId = preId;
    }
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PreOrientationStaffId) ) return false;
		 PreOrientationStaffId castOther = ( PreOrientationStaffId ) other; 
         
		 return (this.getPreId()==castOther.getPreId())
 && (this.getStaffId()==castOther.getStaffId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPreId();
         result = 37 * result + this.getStaffId();
         return result;
   }   


}


