package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * PreOrientationAlertHistoryId generated by hbm2java
 */
public class PreOrientationAlertHistoryId  implements java.io.Serializable {


     private StaffMember staffId;
     private PreOrientation preId;
     private Alert alertId;

    public PreOrientationAlertHistoryId() {
    }

    public PreOrientationAlertHistoryId(StaffMember staffId, PreOrientation preId, Alert alertId) {
       this.staffId = staffId;
       this.preId = preId;
       this.alertId = alertId;
    }
   
    public StaffMember getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(StaffMember staffId) {
        this.staffId = staffId;
    }
    public PreOrientation getPreId() {
        return this.preId;
    }
    
    public void setPreId(PreOrientation preId) {
        this.preId = preId;
    }
    public Alert getAlertId() {
        return this.alertId;
    }
    
    public void setAlertId(Alert alertId) {
        this.alertId = alertId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PreOrientationAlertHistoryId) ) return false;
		 PreOrientationAlertHistoryId castOther = ( PreOrientationAlertHistoryId ) other; 
         
		 return (this.getStaffId()==castOther.getStaffId())
 && (this.getPreId()==castOther.getPreId())
 && (this.getAlertId()==castOther.getAlertId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.staffId.getStaffId();
         result = 37 * result + this.preId.getPreId();
         result = 37 * result + this.alertId.getAlertId();
         return result;
   }   


}


