package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PreOrientation generated by hbm2java
 */
public class PreOrientation  implements java.io.Serializable {


     private Short preId;
     private Department department;
     private Program program;
     private Session session;
     private Center center;
     private Date preDate;
     private Date preYear;

    public PreOrientation() {
    }

    public PreOrientation(Department department, Program program, Session session, Center center, Date preDate, Date preYear) {
       this.department = department;
       this.program = program;
       this.session = session;
       this.center = center;
       this.preDate = preDate;
       this.preYear = preYear;
    }
   
    public Short getPreId() {
        return this.preId;
    }
    
    public void setPreId(Short preId) {
        this.preId = preId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }
    public Date getPreDate() {
        return this.preDate;
    }
    
    public void setPreDate(Date preDate) {
        this.preDate = preDate;
    }
    public Date getPreYear() {
        return this.preYear;
    }
    
    public void setPreYear(Date preYear) {
        this.preYear = preYear;
    }




}


