package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * PreOrientationStaff generated by hbm2java
 */
public class PreOrientationStaff  implements java.io.Serializable {


     private PreOrientationStaffId id;
     private String applyStatus;
     private Short points;

    public PreOrientationStaff() {
    }

	
    public PreOrientationStaff(PreOrientationStaffId id, String applyStatus) {
        this.id = id;
        this.applyStatus = applyStatus;
    }
    public PreOrientationStaff(PreOrientationStaffId id, String applyStatus, Short points) {
       this.id = id;
       this.applyStatus = applyStatus;
       this.points = points;
    }
   
    public PreOrientationStaffId getId() {
        return this.id;
    }
    
    public void setId(PreOrientationStaffId id) {
        this.id = id;
    }
    public String getApplyStatus() {
        return this.applyStatus;
    }
    
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus;
    }
    public Short getPoints() {
        return this.points;
    }
    
    public void setPoints(Short points) {
        this.points = points;
    }




}


