package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program  implements java.io.Serializable {


     private Short programId;
     private String programName;
     private Set<Registration> registrations = new HashSet<Registration>(0);
     private Set<PreOrientation> preOrientations = new HashSet<PreOrientation>(0);
     private Set<LearningToLearn> learningToLearns = new HashSet<LearningToLearn>(0);

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 83 * hash + (this.programId != null ? this.programId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Program other = (Program) obj;
        if (this.programId != other.programId && (this.programId == null || !this.programId.equals(other.programId))) {
            return false;
        }
        return true;
    }

    public Program() {
    }

	
    public Program(String programName) {
        this.programName = programName;
    }
    public Program(String programName, Set<Registration> registrations, Set<PreOrientation> preOrientations, Set<LearningToLearn> learningToLearns) {
       this.programName = programName;
       this.registrations = registrations;
       this.preOrientations = preOrientations;
       this.learningToLearns = learningToLearns;
    }
   
    public Short getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(Short programId) {
        this.programId = programId;
    }
    public String getProgramName() {
        return this.programName;
    }
    
    public void setProgramName(String programName) {
        this.programName = programName;
    }
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }
    public Set<PreOrientation> getPreOrientations() {
        return this.preOrientations;
    }
    
    public void setPreOrientations(Set<PreOrientation> preOrientations) {
        this.preOrientations = preOrientations;
    }
    public Set<LearningToLearn> getLearningToLearns() {
        return this.learningToLearns;
    }
    
    public void setLearningToLearns(Set<LearningToLearn> learningToLearns) {
        this.learningToLearns = learningToLearns;
    }

    @Override
    public String toString() {
        return "Program{" + "programId=" + programId + ", programName=" + programName + '}';
    }




}


