package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistrationCriteriaId generated by hbm2java
 */
public class RegistrationCriteriaId  implements java.io.Serializable {


     private short regId;
     private short workTypeId;

    public RegistrationCriteriaId() {
    }

    public RegistrationCriteriaId(short regId, short workTypeId) {
       this.regId = regId;
       this.workTypeId = workTypeId;
    }
   
    public short getRegId() {
        return this.regId;
    }
    
    public void setRegId(short regId) {
        this.regId = regId;
    }
    public short getWorkTypeId() {
        return this.workTypeId;
    }
    
    public void setWorkTypeId(short workTypeId) {
        this.workTypeId = workTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistrationCriteriaId) ) return false;
		 RegistrationCriteriaId castOther = ( RegistrationCriteriaId ) other; 
         
		 return (this.getRegId()==castOther.getRegId())
 && (this.getWorkTypeId()==castOther.getWorkTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegId();
         result = 37 * result + this.getWorkTypeId();
         return result;
   }   


}


