package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistationStaffId generated by hbm2java
 */
public class RegistationStaffId  implements java.io.Serializable {


     private short regId;
     private short staffId;

    public RegistationStaffId() {
    }

    public RegistationStaffId(short regId, short staffId) {
       this.regId = regId;
       this.staffId = staffId;
    }
   
    public short getRegId() {
        return this.regId;
    }
    
    public void setRegId(short regId) {
        this.regId = regId;
    }
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistationStaffId) ) return false;
		 RegistationStaffId castOther = ( RegistationStaffId ) other; 
         
		 return (this.getRegId()==castOther.getRegId())
 && (this.getStaffId()==castOther.getStaffId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegId();
         result = 37 * result + this.getStaffId();
         return result;
   }   


}


