package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration  implements java.io.Serializable {


     private short regId;
     private Department department;
     private Program program;
     private Sessioninfo sessioninfo;
     private RegistrationType registrationType;
     private Center center;
     private Date regDate;
     private short regYear;
     private String distribution;
     private Set<WorkType> workTypes = new HashSet<WorkType>(0);
     private Set<RegistrationAlertHistory> registrationAlertHistories = new HashSet<RegistrationAlertHistory>(0);
     private Set<RegistrationStaffAvailability> registrationStaffAvailabilities = new HashSet<RegistrationStaffAvailability>(0);
     private Set<RegistrationStaff> registrationStaffs = new HashSet<RegistrationStaff>(0);
     private Set<RegistrationStaffCat> registrationStaffCats = new HashSet<RegistrationStaffCat>(0);

    public Registration() {
    }

	
    public Registration(short regId, Department department, Program program, Sessioninfo sessioninfo, RegistrationType registrationType, Center center, Date regDate, short regYear, String distribution) {
        this.regId = regId;
        this.department = department;
        this.program = program;
        this.sessioninfo = sessioninfo;
        this.registrationType = registrationType;
        this.center = center;
        this.regDate = regDate;
        this.regYear = regYear;
        this.distribution = distribution;
    }
    public Registration(short regId, Department department, Program program, Sessioninfo sessioninfo, RegistrationType registrationType, Center center, Date regDate, short regYear, String distribution, Set<WorkType> workTypes, Set<RegistrationAlertHistory> registrationAlertHistories, Set<RegistrationStaffAvailability> registrationStaffAvailabilities, Set<RegistrationStaff> registrationStaffs, Set<RegistrationStaffCat> registrationStaffCats) {
       this.regId = regId;
       this.department = department;
       this.program = program;
       this.sessioninfo = sessioninfo;
       this.registrationType = registrationType;
       this.center = center;
       this.regDate = regDate;
       this.regYear = regYear;
       this.distribution = distribution;
       this.workTypes = workTypes;
       this.registrationAlertHistories = registrationAlertHistories;
       this.registrationStaffAvailabilities = registrationStaffAvailabilities;
       this.registrationStaffs = registrationStaffs;
       this.registrationStaffCats = registrationStaffCats;
    }
   
    public short getRegId() {
        return this.regId;
    }
    
    public void setRegId(short regId) {
        this.regId = regId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public Sessioninfo getSessioninfo() {
        return this.sessioninfo;
    }
    
    public void setSessioninfo(Sessioninfo sessioninfo) {
        this.sessioninfo = sessioninfo;
    }
    public RegistrationType getRegistrationType() {
        return this.registrationType;
    }
    
    public void setRegistrationType(RegistrationType registrationType) {
        this.registrationType = registrationType;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    public short getRegYear() {
        return this.regYear;
    }
    
    public void setRegYear(short regYear) {
        this.regYear = regYear;
    }
    public String getDistribution() {
        return this.distribution;
    }
    
    public void setDistribution(String distribution) {
        this.distribution = distribution;
    }
    public Set<WorkType> getWorkTypes() {
        return this.workTypes;
    }
    
    public void setWorkTypes(Set<WorkType> workTypes) {
        this.workTypes = workTypes;
    }
    public Set<RegistrationAlertHistory> getRegistrationAlertHistories() {
        return this.registrationAlertHistories;
    }
    
    public void setRegistrationAlertHistories(Set<RegistrationAlertHistory> registrationAlertHistories) {
        this.registrationAlertHistories = registrationAlertHistories;
    }
    public Set<RegistrationStaffAvailability> getRegistrationStaffAvailabilities() {
        return this.registrationStaffAvailabilities;
    }
    
    public void setRegistrationStaffAvailabilities(Set<RegistrationStaffAvailability> registrationStaffAvailabilities) {
        this.registrationStaffAvailabilities = registrationStaffAvailabilities;
    }
    public Set<RegistrationStaff> getRegistrationStaffs() {
        return this.registrationStaffs;
    }
    
    public void setRegistrationStaffs(Set<RegistrationStaff> registrationStaffs) {
        this.registrationStaffs = registrationStaffs;
    }
    public Set<RegistrationStaffCat> getRegistrationStaffCats() {
        return this.registrationStaffCats;
    }
    
    public void setRegistrationStaffCats(Set<RegistrationStaffCat> registrationStaffCats) {
        this.registrationStaffCats = registrationStaffCats;
    }

    private static class RegistrationStaff {

        public RegistrationStaff() {
        }
    }




}


