package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistrationCriteria generated by hbm2java
 */
public class RegistrationCriteria  implements java.io.Serializable {


     private RegistrationCriteriaId id;

    public RegistrationCriteria() {
    }

    public RegistrationCriteria(RegistrationCriteriaId id) {
       this.id = id;
    }
   
    public RegistrationCriteriaId getId() {
        return this.id;
    }
    
    public void setId(RegistrationCriteriaId id) {
        this.id = id;
    }




}


