package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistrationStaffCat generated by hbm2java
 */
public class RegistrationStaffCat  implements java.io.Serializable {


     private RegistrationStaffCatId id;
     private int noOfMembers;
     private int acantSlots;

    public RegistrationStaffCat() {
    }

    public RegistrationStaffCat(RegistrationStaffCatId id, int noOfMembers, int acantSlots) {
       this.id = id;
       this.noOfMembers = noOfMembers;
       this.acantSlots = acantSlots;
    }
   
    public RegistrationStaffCatId getId() {
        return this.id;
    }
    
    public void setId(RegistrationStaffCatId id) {
        this.id = id;
    }
    public int getNoOfMembers() {
        return this.noOfMembers;
    }
    
    public void setNoOfMembers(int noOfMembers) {
        this.noOfMembers = noOfMembers;
    }
    public int getAcantSlots() {
        return this.acantSlots;
    }
    
    public void setAcantSlots(int acantSlots) {
        this.acantSlots = acantSlots;
    }




}


