package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistrationStaffCatId generated by hbm2java
 */
public class RegistrationStaffCatId  implements java.io.Serializable {


     private short regId;
     private short staffCatId;
     private short deptId;

    public RegistrationStaffCatId() {
    }

    public RegistrationStaffCatId(short regId, short staffCatId, short deptId) {
       this.regId = regId;
       this.staffCatId = staffCatId;
       this.deptId = deptId;
    }
   
    public short getRegId() {
        return this.regId;
    }
    
    public void setRegId(short regId) {
        this.regId = regId;
    }
    public short getStaffCatId() {
        return this.staffCatId;
    }
    
    public void setStaffCatId(short staffCatId) {
        this.staffCatId = staffCatId;
    }
    public short getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(short deptId) {
        this.deptId = deptId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistrationStaffCatId) ) return false;
		 RegistrationStaffCatId castOther = ( RegistrationStaffCatId ) other; 
         
		 return (this.getRegId()==castOther.getRegId())
 && (this.getStaffCatId()==castOther.getStaffCatId())
 && (this.getDeptId()==castOther.getDeptId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegId();
         result = 37 * result + this.getStaffCatId();
         result = 37 * result + this.getDeptId();
         return result;
   }   


}


