package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistrationStaffAvailabilityId generated by hbm2java
 */
public class RegistrationStaffAvailabilityId  implements java.io.Serializable {


     private short regId;
     private short staffId;
     private short dayTypeId;

    public RegistrationStaffAvailabilityId() {
    }

    public RegistrationStaffAvailabilityId(short regId, short staffId, short dayTypeId) {
       this.regId = regId;
       this.staffId = staffId;
       this.dayTypeId = dayTypeId;
    }
   
    public short getRegId() {
        return this.regId;
    }
    
    public void setRegId(short regId) {
        this.regId = regId;
    }
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }
    public short getDayTypeId() {
        return this.dayTypeId;
    }
    
    public void setDayTypeId(short dayTypeId) {
        this.dayTypeId = dayTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RegistrationStaffAvailabilityId) ) return false;
		 RegistrationStaffAvailabilityId castOther = ( RegistrationStaffAvailabilityId ) other; 
         
		 return (this.getRegId()==castOther.getRegId())
 && (this.getStaffId()==castOther.getStaffId())
 && (this.getDayTypeId()==castOther.getDayTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRegId();
         result = 37 * result + this.getStaffId();
         result = 37 * result + this.getDayTypeId();
         return result;
   }   


}


