package org.dutyroster.hibernate.database;
// Generated Oct 22, 2013 12:18:18 PM by Hibernate Tools 3.2.1.GA



/**
 * RegistrationStaff generated by hbm2java
 */
public class RegistrationStaff  implements java.io.Serializable {


     private RegistrationStaffId id;
     private StaffMember staffMember;
     private Registration registration;
     private String applyStatus;
     private short points;

    public RegistrationStaff() {
    }

    public RegistrationStaff(RegistrationStaffId id, StaffMember staffMember, Registration registration, String applyStatus, short points) {
       this.id = id;
       this.staffMember = staffMember;
       this.registration = registration;
       this.applyStatus = applyStatus;
       this.points = points;
    }
   
    public RegistrationStaffId getId() {
        return this.id;
    }
    
    public void setId(RegistrationStaffId id) {
        this.id = id;
    }
    public StaffMember getStaffMember() {
        return this.staffMember;
    }
    
    public void setStaffMember(StaffMember staffMember) {
        this.staffMember = staffMember;
    }
    public Registration getRegistration() {
        return this.registration;
    }
    
    public void setRegistration(Registration registration) {
        this.registration = registration;
    }
    public String getApplyStatus() {
        return this.applyStatus;
    }
    
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus;
    }
    public short getPoints() {
        return this.points;
    }
    
    public void setPoints(short points) {
        this.points = points;
    }




}


