package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private Short sessionId;
     private String sessionDesc;
     private Date fromTime;
     private Date toTime;
     private Set<Registration> registrations = new HashSet<Registration>(0);
     private Set<PreOrientation> preOrientations = new HashSet<PreOrientation>(0);
     private Set<LearningToLearn> learningToLearns = new HashSet<LearningToLearn>(0);

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + (this.sessionId != null ? this.sessionId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Session other = (Session) obj;
        if (this.sessionId != other.sessionId && (this.sessionId == null || !this.sessionId.equals(other.sessionId))) {
            return false;
        }
        return true;
    }

    public Session() {
    }

	
    public Session(String sessionDesc) {
        this.sessionDesc = sessionDesc;
    }
    public Session(String sessionDesc, Date fromTime, Date toTime, Set<Registration> registrations, Set<PreOrientation> preOrientations, Set<LearningToLearn> learningToLearns) {
       this.sessionDesc = sessionDesc;
       this.fromTime = fromTime;
       this.toTime = toTime;
       this.registrations = registrations;
       this.preOrientations = preOrientations;
       this.learningToLearns = learningToLearns;
    }
   
    public Short getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(Short sessionId) {
        this.sessionId = sessionId;
    }
    public String getSessionDesc() {
        return this.sessionDesc;
    }
    
    public void setSessionDesc(String sessionDesc) {
        this.sessionDesc = sessionDesc;
    }
    public Date getFromTime() {
        return this.fromTime;
    }
    
    public void setFromTime(Date fromTime) {
        this.fromTime = fromTime;
    }
    public Date getToTime() {
        return this.toTime;
    }
    
    public void setToTime(Date toTime) {
        this.toTime = toTime;
    }
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }
    public Set<PreOrientation> getPreOrientations() {
        return this.preOrientations;
    }
    
    public void setPreOrientations(Set<PreOrientation> preOrientations) {
        this.preOrientations = preOrientations;
    }
    public Set<LearningToLearn> getLearningToLearns() {
        return this.learningToLearns;
    }
    
    public void setLearningToLearns(Set<LearningToLearn> learningToLearns) {
        this.learningToLearns = learningToLearns;
    }

    @Override
    public String toString() {
        return "Session{" + "sessionId=" + sessionId + ", sessionDesc=" + sessionDesc + '}';
    }

    



}


