package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * StaffLanguageId generated by hbm2java
 */
public class StaffLanguageId  implements java.io.Serializable {


     private short staffId;
     private short lanId;

    public StaffLanguageId() {
    }

    public StaffLanguageId(short staffId, short lanId) {
       this.staffId = staffId;
       this.lanId = lanId;
    }
   
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }
    public short getLanId() {
        return this.lanId;
    }
    
    public void setLanId(short lanId) {
        this.lanId = lanId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StaffLanguageId) ) return false;
		 StaffLanguageId castOther = ( StaffLanguageId ) other; 
         
		 return (this.getStaffId()==castOther.getStaffId())
 && (this.getLanId()==castOther.getLanId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStaffId();
         result = 37 * result + this.getLanId();
         return result;
   }   


}


