package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * StaffMember generated by hbm2java
 */
public class StaffMember  implements java.io.Serializable {


     private Short staffId;
     private Department department;
     private UserRole userRole;
     private StaffCategory staffCategory;
     private Center center;
     private String initials;
     private String surname;
     private Integer officePhone;
     private Integer mobile;
     private String officeEmail;

    public StaffMember() {
    }

	
    public StaffMember(Department department, UserRole userRole, StaffCategory staffCategory, Center center, String initials, String surname) {
        this.department = department;
        this.userRole = userRole;
        this.staffCategory = staffCategory;
        this.center = center;
        this.initials = initials;
        this.surname = surname;
    }
    public StaffMember(Department department, UserRole userRole, StaffCategory staffCategory, Center center, String initials, String surname, Integer officePhone, Integer mobile, String officeEmail) {
       this.department = department;
       this.userRole = userRole;
       this.staffCategory = staffCategory;
       this.center = center;
       this.initials = initials;
       this.surname = surname;
       this.officePhone = officePhone;
       this.mobile = mobile;
       this.officeEmail = officeEmail;
    }
   
    public Short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Short staffId) {
        this.staffId = staffId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }
    public StaffCategory getStaffCategory() {
        return this.staffCategory;
    }
    
    public void setStaffCategory(StaffCategory staffCategory) {
        this.staffCategory = staffCategory;
    }
    public Center getCenter() {
        return this.center;
    }
    
    public void setCenter(Center center) {
        this.center = center;
    }
    public String getInitials() {
        return this.initials;
    }
    
    public void setInitials(String initials) {
        this.initials = initials;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public Integer getOfficePhone() {
        return this.officePhone;
    }
    
    public void setOfficePhone(Integer officePhone) {
        this.officePhone = officePhone;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public String getOfficeEmail() {
        return this.officeEmail;
    }
    
    public void setOfficeEmail(String officeEmail) {
        this.officeEmail = officeEmail;
    }




}


