package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * StaffLanguage generated by hbm2java
 */
public class StaffLanguage  implements java.io.Serializable {


     private StaffLanguageId id;
     private short proficiency;

    public StaffLanguage() {
    }

    public StaffLanguage(StaffLanguageId id, short proficiency) {
       this.id = id;
       this.proficiency = proficiency;
    }
   
    public StaffLanguageId getId() {
        return this.id;
    }
    
    public void setId(StaffLanguageId id) {
        this.id = id;
    }
    public short getProficiency() {
        return this.proficiency;
    }
    
    public void setProficiency(short proficiency) {
        this.proficiency = proficiency;
    }




}


