package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Short roleId;
     private String roleName;
     private Set<StaffMember> staffMembers = new HashSet<StaffMember>(0);

    public UserRole() {
    }

	
    public UserRole(String roleName) {
        this.roleName = roleName;
    }
    public UserRole(String roleName, Set<StaffMember> staffMembers) {
       this.roleName = roleName;
       this.staffMembers = staffMembers;
    }
   
    public Short getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Short roleId) {
        this.roleId = roleId;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public Set<StaffMember> getStaffMembers() {
        return this.staffMembers;
    }
    
    public void setStaffMembers(Set<StaffMember> staffMembers) {
        this.staffMembers = staffMembers;
    }




}


