package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * UserAccount generated by hbm2java
 */
public class UserAccount  implements java.io.Serializable {


     private String userName;
     private short staffId;
     private String password;

    public UserAccount() {
    }

    public UserAccount(String userName, short staffId, String password) {
       this.userName = userName;
       this.staffId = staffId;
       this.password = password;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


