package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * Workstation generated by hbm2java
 */
public class Workstation  implements java.io.Serializable {


     private Short workstationId;
     private String workstationName;

    public Workstation() {
    }

    public Workstation(String workstationName) {
       this.workstationName = workstationName;
    }
   
    public Short getWorkstationId() {
        return this.workstationId;
    }
    
    public void setWorkstationId(Short workstationId) {
        this.workstationId = workstationId;
    }
    public String getWorkstationName() {
        return this.workstationName;
    }
    
    public void setWorkstationName(String workstationName) {
        this.workstationName = workstationName;
    }




}


