package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * WorkType generated by hbm2java
 */
public class WorkType  implements java.io.Serializable {


     private Short workTypeId;
     private String workTypeName;
     private float percentage;

    public WorkType() {
    }

    public WorkType(String workTypeName, float percentage) {
       this.workTypeName = workTypeName;
       this.percentage = percentage;
    }
   
    public Short getWorkTypeId() {
        return this.workTypeId;
    }
    
    public void setWorkTypeId(Short workTypeId) {
        this.workTypeId = workTypeId;
    }
    public String getWorkTypeName() {
        return this.workTypeName;
    }
    
    public void setWorkTypeName(String workTypeName) {
        this.workTypeName = workTypeName;
    }
    public float getPercentage() {
        return this.percentage;
    }
    
    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }




}


