package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * WorkstationPriorityId generated by hbm2java
 */
public class WorkstationPriorityId  implements java.io.Serializable {


     private short staffId;
     private short workstationId;
     private short deptId;

    public WorkstationPriorityId() {
    }

    public WorkstationPriorityId(short staffId, short workstationId, short deptId) {
       this.staffId = staffId;
       this.workstationId = workstationId;
       this.deptId = deptId;
    }
   
    public short getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(short staffId) {
        this.staffId = staffId;
    }
    public short getWorkstationId() {
        return this.workstationId;
    }
    
    public void setWorkstationId(short workstationId) {
        this.workstationId = workstationId;
    }
    public short getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(short deptId) {
        this.deptId = deptId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WorkstationPriorityId) ) return false;
		 WorkstationPriorityId castOther = ( WorkstationPriorityId ) other; 
         
		 return (this.getStaffId()==castOther.getStaffId())
 && (this.getWorkstationId()==castOther.getWorkstationId())
 && (this.getDeptId()==castOther.getDeptId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStaffId();
         result = 37 * result + this.getWorkstationId();
         result = 37 * result + this.getDeptId();
         return result;
   }   


}


