package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;


/**
 * WorkType generated by hbm2java
 */
public class WorkType implements java.io.Serializable {

   private short workTypeId;
     private String workTypeName;
     private float workPercentage;
     private Set<Registration> registrations = new HashSet<Registration>(0);

    public WorkType() {
    }

	
    public WorkType(short workTypeId, String workTypeName, float workPercentage) {
        this.workTypeId = workTypeId;
        this.workTypeName = workTypeName;
        this.workPercentage = workPercentage;
    }
    public WorkType(short workTypeId, String workTypeName, float workPercentage, Set<Registration> registrations) {
       this.workTypeId = workTypeId;
       this.workTypeName = workTypeName;
       this.workPercentage = workPercentage;
       this.registrations = registrations;
    }
   
    public short getWorkTypeId() {
        return this.workTypeId;
    }
    
    public void setWorkTypeId(short workTypeId) {
        this.workTypeId = workTypeId;
    }
    public String getWorkTypeName() {
        return this.workTypeName;
    }
    
    public void setWorkTypeName(String workTypeName) {
        this.workTypeName = workTypeName;
    }
    public float getWorkPercentage() {
        return this.workPercentage;
    }
    
    public void setWorkPercentage(float workPercentage) {
        this.workPercentage = workPercentage;
    }
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }

}
