package org.dutyroster.hibernate.database;
// Generated Oct 6, 2013 6:54:13 PM by Hibernate Tools 3.2.1.GA



/**
 * WorkstationPriority generated by hbm2java
 */
public class WorkstationPriority  implements java.io.Serializable {


     private WorkstationPriorityId id;

    public WorkstationPriority() {
    }

    public WorkstationPriority(WorkstationPriorityId id) {
       this.id = id;
    }
   
    public WorkstationPriorityId getId() {
        return this.id;
    }
    
    public void setId(WorkstationPriorityId id) {
        this.id = id;
    }




}


